name: Release
on:
  release:
    types:
      - created
# https://dev.to/erikhofer/build-and-publish-a-multi-platform-electron-app-on-github-3lnd
jobs:
  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish
